server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://ewm-db:5432/ewm
    username: ewm
    password: ewm
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: WARN
    org.springframework.orm.jpa.JpaTransactionManager: INFO
    org.zalando.logbook: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: WARN
